push_tests:
  script:
    - echo "Tests started at $(date)"
    - sleep 10
    - echo "Tests ended at $(date)"

build_image:
  script:
    - echo "Build started at $(date)"
    - sleep 10
    - echo "Build ended at $(date)"

push_image:
  script:
    - echo "Push started at $(date)" 
    - sleep 10
    - echo "Push ended at $(date)"