stages: [ build ]

push_image:
  stage: build
  tags:
  - ec2
  - shell
  - remote
  script:
  - echo "Docker registry url is: $CI_REGISTRY"
  - echo "Docker registry username is: $CI_REGISTRY_USER"
  - echo "Docker image repository is: $CI_REGISTRY_IMAGE"
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  - docker push "$CI_REGISTRY_IMAGE:1.0"
